# Generated by Django 6.0 on 2025-12-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_fio', models.CharField(max_length=255)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('login', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_name', models.CharField(max_length=255)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'discounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_productivity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('login', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_current', models.IntegerField()),
                ('quantity_in_transit', models.IntegerField()),
                ('product_date_of_receipt', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('order_items_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_channel', models.CharField(max_length=50)),
                ('order_status', models.TextField()),
                ('order_finished', models.BooleanField()),
                ('client_feedback', models.TextField(blank=True, null=True)),
                ('order_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price_for_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_possibility', models.TextField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Redactors',
            fields=[
                ('redactor_id', models.AutoField(primary_key=True, serialize=False)),
                ('redactor_name', models.CharField(max_length=255)),
                ('redactor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('redactor_position', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'redactors',
                'managed': False,
            },
        ),
    ]
