# Generated by Django 6.0 on 2025-12-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20251210_1754'),
    ]

    operations = [
    ]
